version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: solarview-login-nginx
    working_dir: /var/www/html
    build:
      context: ./docker/nginx/
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx:/etc/nginx/templates
      - ./docker/nginx/startup.sh:/docker-entrypoint.d/startup.sh
      - ./:/var/www/html
    environment:
      - NGINX_HOST=solarview-login.com
      - NGINX_PORT=80
    networks:
      - solarview_login_default_network
    depends_on:
      - mysql
      - redis

  mysql:
    container_name: solarview-login-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=solarview-login-db
      - MYSQL_ROOT_PASSWORD=admin123
    ports:
      - "3309:3306"
    networks:
      - solarview_login_default_network

  redis:
    image: redis
    container_name: solarview-login-redis
    ports:
      - "6382:6379"
    networks:
      - solarview_login_default_network

networks:
  solarview_login_default_network:
    name: solarview_login_default_network
